### ISSUE TITLE
Quarriers are not digging quarries 

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/minecolonies#10562]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1..20.1.1.1778

### Structurize Version

1.20.1-1.0.763

### Current Behavior

Quarrier will request all matierials for the quarry shaft but will not dig the hole and build the quarry -shaft
on raid-christmas server
initially my quarrier went down 6 levels and said he was done and needed to be assigned to a new quarry,  I am not sure if that issue was fixed this was in my own raid colony,  we deconstructed the quarry and gave up
next in the christmas colony the quarrier requested all materials but would not build the quarry,  with much babysitting and firing and rehiring and removing snow for him - he dug down three levels,  does not ever say he is done,  but stands around,  with all the framed blocks shovel and pickaxe in inventory,  no complaints, no requests just will not dig we put the christmas themed quarry deco over it and gave up
 mentioned this and was asked to create github,  forgot to do that,   built a new quarry to make sure it wasn't already fixed, 
 Quarrier requested tools and materials and is just standing there,  refusing to dig , no complaints and no requests 

### Expected Behavior

I would expect them to dig a hole and make the quarry-shaft after getting all the materials 

### Reproduction Steps

log into christmas server
go to the quarry which is near the wall south side of colony
watch the quarrier 

### Logs

Christmas server

### Anything else?

it is the functional fantasy simple quarry
I will try building a medium quarry to see if that will work since the builders are all bored
it has been 3 quarries attempted all on same server but I have and others have built this quarry before in survival with no problems so I do not think it could be the schematic

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by anastasia590** [comment]
adding to confirm that in addition to trying the functional fantasy simple quarry the minecolonies original medium quarry is also not working,   the quarrier requested the framed blocks and ladders to make it , and is now just standing there  has tools, no open requests - firing and rehiring causes them to pretend to work for a second or two then they stop
 Christmas colony, winter(raid) server

**Comment by Raycoms** [comment]
fixed on latest

**Comment by Mapettv** [comment]
The issue still occurs on minecolonies-1.1.857-1.21.1-snapshot. The villager works for a while, and when he starts digging with his shovel after one dug block he stops. After restarting or reemploying, the villager digs one block again and stops.
