### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by N0cturnal** [ldtteam/minecolonies#10899]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.21

### MineColonies Version

1.1.972-1.21.1-snapshot

### Structurize Version

1.0.774-1.21.1-snapshot

### Reproduction Steps

One of the npc's ran into an error with their AI

### Logs

https://pastebin.com/fRMMbdGg

### Anything else?

![Image](https://github.com/user-attachments/assets/9e55c093-fd9e-43be-8198-d909bbddba9e)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This has been fixed already

**Comment by PerksPrisoner** [comment]
This is still an issue as of 15.1 and when updating to 15.2 the server goes into a death roll

**Comment by Raycoms** [comment]
15.1?

**Comment by Raycoms** [comment]
Fixed with newest
