### ISSUE TITLE
Buggy Builder

### ISSUE THREAD

**Issue by Supermatt5546** [ldtteam/minecolonies#1382]
### Minecolonies version: minecolonies-universal-1.12-0.8.3302

As you can tell, I'm playing on 1.12 with version 1.12-14.21.1.2443 of Forge.

### Steps to reproduce the problem

1. I hired the builder.
2. Built his hut.
3. Chose to build the Guard tower/ upgrade the hut/ build the gate for each of the issues, with the gate issue happening with 4 separate colonists.
4. Profit

**Comment by Raycoms** [comment]
When they hold the object they don't even have, that's because that's the
next one they're going to use, and we left it in so players can detect what
they might be needing

2017-08-20 23:33 GMT+01:00 Supermatt5546 <notifications@github.com>:

**Comment by Supermatt5546** [comment]
I know the purpose. I'm talking about when they hold the item they don't actually have, & just wonder aimlessly when I actually give them the item. They will even hold it when they're no longer a builder.

**Comment by Raycoms** [comment]
Yeah, that's because they're still in requesting mode and will only leave
it when they receive that item somehow.

2017-08-20 23:56 GMT+01:00 Supermatt5546 <notifications@github.com>:

**Comment by Supermatt5546** [comment]
Yeah, but even when they have the item, they don't do anything. Even if they're assigned to another project or even another job entirely, they will still be holding the item.

**Comment by Raycoms** [comment]
Yes, like I said, they still request it. Only restart should solve it.

2017-08-21 0:15 GMT+01:00 Supermatt5546 <notifications@github.com>:

**Comment by Supermatt5546** [comment]
Restart what? The game? That solved nothing. Giving them another job doesn't fix it either. They may function fine with their new job, but they will still be broken as the builder.

**Comment by Raycoms** [comment]
Having an item in the hand isn't what I'd call "broken".

2017-08-21 0:21 GMT+01:00 Supermatt5546 <notifications@github.com>:

**Comment by Supermatt5546** [comment]
Did you not read where I pointed out that them simply holding the item isn't the issue? It's that they hold the item that isn't actually there & do nothing, even when the required number is given to them. They do nothing at all,regardless of what they're told to do.

**Comment by Raycoms** [comment]
Then they're probably waiting for another type of item. Nevertheless, they
should request it, but, when you fire them in that process that request
might get lost at the dman.

**Comment by Supermatt5546** [comment]
I don't think that's the case. I tend to give them everything they need in advance, & he would still wonder around aimlessly. In the case of where the gate should go, he removed the torches I placed at the site, & then just stares at it with a pick or shovel in hand.

**Comment by Raycoms** [comment]
Can you please supply us some more information :

Do /mc colonies list to get the colony id, then /mc citizens citizeninfo
colonyid nameofcitizen to see which state he is in and lastly does the log
say anything?

**Comment by Supermatt5546** [comment]
I'm confused. When typing that, all that came up was <list:kill:respawn:info>

**Comment by Asherslab** [comment]
Yes /mc citizens info should work (after getting the ID/name from /mc citizens list

**Comment by Raycoms** [comment]
Then do mc citizens info

**Comment by Supermatt5546** [comment]
His activity says "Clear_Step" instead of "Start_Working".

**Comment by Supermatt5546** [comment]
Ok, I cleared the foundation for him, since he couldn't do his job. I also fired him & rehired him another 20 times & he actually started building the stone gate finally. Might mark the days before he breaks again.

**Comment by Raycoms** [comment]
this is very strange, he normally doesn't behave like that. Please send us
your full log. I believe there might be a block he wasn't able to clear.

2017-08-21 17:51 GMT+01:00 Supermatt5546 <notifications@github.com>:

**Comment by Supermatt5546** [comment]
I have a number of archives in my Logs folder. Do I give the most resent or all of them? Also the Builder is doing a similar thing again, but with torches in his hand while staring at the gate, which has been built up to the point where the chandeliers are floating in the center.

**Comment by Asherslab** [comment]
latest.txt (if you played the mod last)

**Comment by Supermatt5546** [comment]
[00:16:16] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3824ms behind, skipping 76 tick(s)
[00:16:59] [Server thread/INFO]: Saving and pausing game...
[00:17:00] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:17:00] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:17:01] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:19:15] [Server thread/INFO]: Saving and pausing game...
[00:19:15] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:19:16] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:19:16] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:19:16] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2194ms behind, skipping 43 tick(s)
[00:19:22] [Server thread/INFO]: Saving and pausing game...
[00:19:22] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:19:23] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:19:23] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:19:26] [Server thread/INFO]: Saving and pausing game...
[00:19:26] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:19:27] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:19:28] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:19:31] [Server thread/INFO]: Saving and pausing game...
[00:19:31] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:19:32] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:19:33] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:22:50] [Server thread/INFO]: Saving and pausing game...
[00:22:50] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:22:51] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:22:52] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:22:52] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2302ms behind, skipping 46 tick(s)
[00:24:37] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2074ms behind, skipping 41 tick(s)
[00:25:23] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2805ms behind, skipping 56 tick(s)
[00:26:08] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2317ms behind, skipping 46 tick(s)
[00:26:54] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2595ms behind, skipping 51 tick(s)
[00:30:39] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2068ms behind, skipping 41 tick(s)
[00:31:24] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2183ms behind, skipping 43 tick(s)
[00:35:09] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2089ms behind, skipping 41 tick(s)
[00:36:39] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2067ms behind, skipping 41 tick(s)
[00:38:09] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2137ms behind, skipping 42 tick(s)
[00:38:55] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2164ms behind, skipping 43 tick(s)
[00:39:18] [Server thread/INFO]: Saving and pausing game...
[00:39:18] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:39:19] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:39:20] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:47:37] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2006ms behind, skipping 40 tick(s)
[00:49:07] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2005ms behind, skipping 40 tick(s)
[00:49:52] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2005ms behind, skipping 40 tick(s)
[00:52:28] [Server thread/INFO]: Saving and pausing game...
[00:52:28] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:52:29] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:52:29] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[00:56:13] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 132384ms behind, skipping 2647 tick(s)
[00:57:02] [Server thread/INFO]: Saving and pausing game...
[00:57:02] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[00:57:03] [Server thread/INFO]: Saving chunks for level 'World1'/the_nether
[00:57:03] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:03:08] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 12293ms behind, skipping 245 tick(s)
[01:03:18] [Server thread/INFO]: Saving and pausing game...
[01:03:18] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:03:20] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:03:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4424ms behind, skipping 88 tick(s)
[01:03:33] [Server thread/INFO]: [DragonbornSSjB : Teleported DragonbornSSjB  to 3303.5, 66.0, 541.5]
[01:03:33] [main/INFO]: [CHAT] Teleported DragonbornSSjB  to 3303.5, 66.0, 541.5
[01:03:40] [main/INFO]: [CHAT] Builder Levi J. Golding: Started building schematics/walls/StoneWallGate
[01:03:45] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 11649ms behind, skipping 232 tick(s)
[01:04:00] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6189ms behind, skipping 123 tick(s)
[01:04:37] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2333ms behind, skipping 46 tick(s)
[01:05:08] [main/INFO]: [CHAT] You need a builder in order to build or upgrade this building.
[01:05:08] [main/INFO]: [CHAT] You need a builder in order to build or upgrade this building.
[01:05:08] [main/INFO]: [CHAT] You need a builder in order to build or upgrade this building.
[01:05:08] [main/INFO]: [CHAT] You need a builder in order to build or upgrade this building.
[01:05:08] [main/INFO]: [CHAT] You need a builder in order to build or upgrade this building.
[01:05:08] [Server thread/INFO]: Saving and pausing game...
[01:05:08] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:05:09] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:05:10] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2495ms behind, skipping 49 tick(s)
[01:05:12] [main/INFO]: [CHAT] Builder Levi J. Golding: Started building schematics/walls/StoneWallGate
[01:05:25] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2583ms behind, skipping 51 tick(s)
[01:05:49] [main/INFO]: [CHAT] Baker Blanche V. Battle: I need Wheat!
[01:06:11] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3003ms behind, skipping 60 tick(s)
[01:06:17] [Server thread/INFO]: [DragonbornSSjB : Set own game mode to Survival Mode]
[01:06:17] [main/INFO]: [CHAT] Your game mode has been updated to Survival Mode
[01:06:21] [main/INFO]: [CHAT] Baker Blanche V. Battle: I need Wheat!
[01:06:57] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2959ms behind, skipping 59 tick(s)
[01:07:45] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4567ms behind, skipping 91 tick(s)
[01:07:54] [Server thread/INFO]: Saving and pausing game...
[01:07:55] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:07:56] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:22:05] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2392ms behind, skipping 47 tick(s)
[01:22:13] [Server thread/INFO]: [DragonbornSSjB : Set own game mode to Creative Mode]
[01:22:13] [main/INFO]: [CHAT] Your game mode has been updated to Creative Mode
[01:22:38] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2688ms behind, skipping 53 tick(s)
[01:22:51] [Server thread/INFO]: Saving and pausing game...
[01:22:51] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:22:52] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:31:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2868ms behind, skipping 57 tick(s)
[01:31:12] [Server thread/INFO]: Saving and pausing game...
[01:31:12] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:31:13] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:35:14] [main/INFO]: [CHAT] /minecolonies <colonies|colony|citizens|rtp|backup|home>
[01:35:23] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4094ms behind, skipping 81 tick(s)
[01:35:25] [main/INFO]: [CHAT] /minecolonies <colonies|colony|citizens|rtp|backup|home>
[01:35:30] [Server thread/INFO]: Saving and pausing game...
[01:35:30] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:35:32] [Server thread/INFO]: Saving chunks for level 'World1'/the_end
[01:42:16] [Server thread/INFO]: Stopping server
[01:42:16] [Server thread/INFO]: Saving players
[01:42:16] [Server thread/INFO]: DragonbornSSjB  lost connection: Disconnected
[01:42:16] [Server thread/INFO]: DragonbornSSjB  left the game
[01:42:16] [Server thread/INFO]: Stopping singleplayer server as player logged out
[01:42:16] [Server thread/INFO]: Saving worlds
[01:42:16] [Server thread/INFO]: Saving chunks for level 'World1'/overworld
[01:42:16] [Server thread/INFO]: Saving chunks for level 'World1'/the_end

**Comment by Supermatt5546** [comment]
Also he continued when I placed the torches on the chandeliers, but stopped a few minutes later.

**Comment by Raycoms** [comment]
Seems like several people have that problem on 1.12

**Comment by hron84** [comment]
Builders have serious problems in 1.11 too. I am not able to stop the current building, nor be able to move him to another project. At some point, he went out of some rare materials and I was not able to provide it atm, but I had a pending warehouse project and I wanted him to move on since he had a plenty of materials for it. I had to break the block of the previous project to enforce them to move, even if I canceled the build and deleted his work order at the city hall. 

Please, give more love for builders because their are the true heart of the colonies.

**Comment by Raycoms** [comment]
The workers have one flaw and that's when they started requesting something they will insist. In this case, cancel the workOrder and fire/rehire, which should resolve the issue.

**Comment by hron84** [comment]
@Raycoms do you plan to improve this?

**Comment by Raycoms** [comment]
We are

2017-08-26 0:03 GMT+01:00 Gabor Garami <notifications@github.com>:

**Comment by DietmarKrause** [comment]
I am not sure if i can help but i had a similar problem with the miner: after several tries at least in my case i found a solution: i recalled the NPC (a miner in my case) and no matter what i put in the chest he dont want to work. BUT: if i take something OUT of his personally inventory (not the chest) he starts working, takes materials out of the chest and works again without asking anything. I had to do that often though.

**Comment by hron84** [comment]
@DietmarKrause thanks, in the new world, if I experience same issue, I'll try it out.

**Comment by DietmarKrause** [comment]
the second solution was : set the hiring system in the town hall to manual. Then fire the worker. After that it is important to take him away everything he/she has in his personal inventory (!) . After that it is typical that he has his former tool in his hand altough there is nothing in the inventory. Now it is important to save and quit then restart the game. After that you can re-hire him and he will work again. But i am almost sure that in the bottom line this is the same as taking away something out of the private inventory.

**Comment by DietmarKrause** [comment]
https://github.com/Minecolonies/minecolonies/issues/1403

**Comment by DietmarKrause** [comment]
https://github.com/Minecolonies/minecolonies/issues/1343
seems emptying out there complete personal inventory works

**Comment by hron84** [comment]
Builders can be fixed with just firing/rehiring (I tested that previously), miner should have a bit different code as he/she does not follow a fixed plan.

**Comment by Raycoms** [comment]
The Miner choose random paths so he is not completely deterministic. Still
fire rehire should fix him

**Comment by hron84** [comment]
@Raycoms I will definitely look into in this week. Btw, Did I got correctly Miner does not limited in Y level in terms of hut level? So Level 1 miner can start mining at Y=25? In a flatland desert world, I'd like to skip sand levels for him to not cause a massive lag.

**Comment by Raycoms** [comment]
There is a limited y in terms of hut level, but he will ask you to upgrade
his hut until he can actually start digging.

2017-08-30 16:14 GMT+01:00 Gabor Garami <notifications@github.com>:

**Comment by hron84** [comment]
Is there more info about Y limits?

**Comment by Raycoms** [comment]
/**
 * Max depth the miner reaches at building level 1.
 */
MAX_DEPTH_LEVEL_0 = 70;

/**
 * Max depth the miner reaches at building level 2.
 */
MAX_DEPTH_LEVEL_1 = 50;

/**
 * Max depth the miner reaches at building level 3.
 */
MAX_DEPTH_LEVEL_2 = 30;


2017-08-30 23:19 GMT+01:00 Gabor Garami <notifications@github.com>:

**Comment by Supermatt5546** [comment]
I had the problem whether I took something out of his inventory or not. To get him to finish building something he was stuck on, I had to help him build it. When stuck in requesting mode, nothing seemed to work.

**Comment by hron84** [comment]
@Raycoms so unupgraded miner can dig deeper than lvl3 one? :open_mouth:

**Comment by Raycoms** [comment]
No, that's the max y level

**Comment by hron84** [comment]
Ohh, I see. Thanks.

**Comment by PhoenixRiver** [comment]
I should mention that the builder is very finicky and to get her to start a different project I have to fire and rehire her, however she usually loses her levels in build when I do this meaning that I have to give her wooden tools to start with again :(

minecolonies-universal-1.12.2-0.8.4932
