### ISSUE TITLE
Building Level 3 Barracks deletes one of the barracks towers

### ISSUE THREAD

**Issue by Neferdias** [ldtteam/minecolonies#1673]
### Minecolonies version

1.12.2-0.8.5088

### Expected behavior

Building the level 3 barracks should build around existing barracks towers.

### Actual behaviour

The barracks tower made available by the Level 2 barracks gets over written and removed as the Level 3 barracks is being built. The level 3 barracks treats the level 2 barracks tower location as the level 4 barracks tower location

### Steps to reproduce the problem

Build up a level 2 barracks.
Build both barracks towers and upgrade them to level 2 (though i don't think this step should matter what level each are at)
Upgrade the barracks to level 3 and watch it delete on of the towers

![2017-11-21_23 08 53](https://user-images.githubusercontent.com/33792638/33112572-2e9bdb18-cf11-11e7-9b7e-85bd941ee455.png)

top corner is where the tower was. I assume it expects it to be in the right position of this picture. adding the level 3 barracks tower in the bottom position

**Comment by MattBeard** [comment]
OK... am I being dumb?

a) This version does not even seem to be in Alpha yet!
b) Barracks? How do we build those in survival?

**Comment by Raycoms** [comment]
Should be fixed

**Comment by zekeflynn** [comment]
Is not fixed. Medieval Birch barracks tier 3 deleted BOTH my towers for whatever reason.

**Comment by PoroUsedSnax** [comment]
This issue is regarding the wooden barracks and has been closed for a bit now, best to open a new issue if there isn't already one for that style, make sure you're on the latest alpha available too
