### ISSUE TITLE
MC Colony Delete command throws null pointer

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/minecolonies#2372]
### Steps to reproduce the problem

1. execute command

https://gist.github.com/Asherslab/f9aa56c68247bbbce593f63166ed85e9

**Comment by mkienenb** [comment]
The error is because the command's senderEntity is null.   Any ideas why that might be the case?  Is this being run by a command block?

        final Entity senderEntity = sender.getCommandSenderEntity();
        senderEntity.sendMessage(new TextComponentString(DELETE_COLONY_TASK_SCHEDULED));

**Comment by Asherslab** [comment]
@mkienenb you were correct in slack, i was running the command via console

**Comment by Asherslab** [comment]
So, i think this is fixed now, so i'm going to close this

**Comment by mkienenb** [comment]
No, it's not fixed until someone merges pr #2373.  Not sure what the hold-up on that is.
