### ISSUE TITLE
Supply Camp placing wrong blocks and no chest

### ISSUE THREAD

**Issue by YogoGeeButch** [ldtteam/minecolonies#3203]
Minecolonies version: 1.12.2-0.10.95-ALPHA
Expected behavior: Supply camp places, using dirt that was on the ground as the base, with a chest near the fire pit containing the Town Hall, and a building tool.
Actual Behavior: placing the supply camp puts the town hall and building tool on the ground, and the entire base is the brown substitute blocks rather than just dirt.

Steps to reproduce the problem
1. Make Supply camp in survival on a normal world.
2. Place supply camp
3. So you can see what I described.

**Comment by Raycoms** [comment]
fixed

**Comment by cjser** [comment]
It not fixed. I build a supply ship and a supply camp in different plays on survival, and both times not get the town hall item.

**Comment by spacewolfcub** [comment]
Even after checking all the chests? 
It might not be showing up in the usual chest.

**Comment by Raycoms** [comment]
In the newest?

Am Di., 15. Jan. 2019 um 13:30 Uhr schrieb spacewolfcub <
notifications@github.com>:

**Comment by cjser** [comment]
In a new play, it appear in the ship. Seems random problem or something was
interfering with showing.
