### ISSUE TITLE
NPC keeping animals do not eat if they have raw meat in their personal inventories

### ISSUE THREAD

**Issue by Fatmice** [ldtteam/minecolonies#3366]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.154-BETA-universal

### Expected behavior

- NPCs keeping animals get raw meat from doing their work.  This meat should be transferred to the hut inventory.

### Actual behaviour

- NPCs keeping animals get raw meat from doing their work.  This meat is not transferred to the hut inventory.  Thus they can't eat because they can not eat raw food until those items are manually removed by the player.

### Steps to reproduce the problem

1. Build a cow ranching hut
2. Assign worker and give wheat
3. After some time, worker will slaughter animals and get hide and raw beef.  These loot are not transferred to the ranching hut inventory.  Worker gets hungry but can't eat because of raw beef.  Left alone, they spam about their inability to eat and will eventually starve to death without player intervention.
4. ... Profit

**Comment by Raycoms** [comment]
Fixed in one of the latest updates

**Comment by Fatmice** [comment]
It is still happening.
minecolonies-1.12.2-0.10.171-ALPHA-universal
![2019-02-18_21 01 48](https://user-images.githubusercontent.com/8956281/52987398-964ee100-33c0-11e9-821b-4cbe193e81ba.png)
![2019-02-18_21 04 33](https://user-images.githubusercontent.com/8956281/52987463-d910b900-33c0-11e9-8128-987145e20e7f.png)

**Comment by Raycoms** [comment]
Should be fixed in a version which is newer than that. I just double checked the git log

**Comment by Fatmice** [comment]
Raw food strikes back
![2019-02-24_17 08 44](https://user-images.githubusercontent.com/8956281/53306983-3ab9a300-3859-11e9-8bab-952936187576.png)
![2019-02-24_17 12 16](https://user-images.githubusercontent.com/8956281/53306984-3ee5c080-3859-11e9-87ed-8814b7d5c4e6.png)
![2019-02-24_17 24 51](https://user-images.githubusercontent.com/8956281/53306987-41e0b100-3859-11e9-8197-4ece58251d56.png)
Seems they are still keeping raw items in their inventory and not dropping them to the hut
minecolonies-1.12.2-0.10.189-BETA-universal

**Comment by Raycoms** [comment]
Oh, they just complain here and there case you put the food in their inventory. Because of that you are only seeing a few in the inventory.

**Comment by Fatmice** [comment]
I didn't put any raw things in their inventory.  This guy got his raw fish from fishing.  But like you say, as long as they put them away and only seldomly have raw things.  I just hope they still eat after they complain but putting the raw things into their hut.

**Comment by Raycoms** [comment]
Yeah, it's difficult to differentiate.

Am Mo., 25. Feb. 2019 um 00:14 Uhr schrieb Fatmice <notifications@github.com

**Comment by Fatmice** [comment]
So here's what's going on.  You will see it's been seven days and the fisherman have not empty his inventory.  He is hungry and has raw items on him.  They are the same raw items that he got from fishing.  I didn't put them there.  What he does is goes to the kitchen everyday and stand there hungry because he doesn't eat due to the fact that he is too stupid to dump the raw stuff at his work hut, which he doesn't go to because he is hungry...Do you see the problem?  This is a logical loop that will never break itself.

![2019-02-24_21 27 14](https://user-images.githubusercontent.com/8956281/53317341-e7634700-3890-11e9-8416-3347eabe129d.png)
![2019-02-24_21 27 19](https://user-images.githubusercontent.com/8956281/53317342-e7634700-3890-11e9-84b9-3a23d88c180e.png)
![2019-02-24_21 27 23](https://user-images.githubusercontent.com/8956281/53317343-e7634700-3890-11e9-9430-4468f36a3220.png)
![2019-02-25_00 03 40](https://user-images.githubusercontent.com/8956281/53317344-e7634700-3890-11e9-86b8-6736ac1b7c6e.png)
![2019-02-25_00 03 43](https://user-images.githubusercontent.com/8956281/53317345-e7fbdd80-3890-11e9-9c9a-7bf6865c18a4.png)
![2019-02-25_00 03 45](https://user-images.githubusercontent.com/8956281/53317346-e7fbdd80-3890-11e9-99c6-8c511a46ee00.png)
