### ISSUE TITLE
Guards not reacting to hostile attacks

### ISSUE THREAD

**Issue by Fatmice** [ldtteam/minecolonies#3384]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.171-ALPHA-universal

### Expected behavior

- Guards should react to hostile attack and engage.

### Actual behaviour

- Guards seems to react more to melee attacks but not range attacks.  They seems to notice the range attack but will not return in kind.  They stand around getting turned into pin cushions.  While this is going on, there are a lot of log spams...I don't know if they are related.  After the barbs are dead from player intervention, the log spam seems to be less...they're still on-going though.

Regarding melee attacks, they will also tend to glitch out and stand there getting beat into mush by barbs.  They do rush at them but after the initial commotion, they often tend to glitch out and will need player intervention or will eventually succumb to barbs.

[debug.zip](https://github.com/ldtteam/minecolonies/files/2866413/debug.zip)
[latest.zip](https://github.com/ldtteam/minecolonies/files/2866414/latest.zip)

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
should be fixed

**Comment by Fatmice** [comment]
Unfortunately, I still see them standing there getting attacked...minecolonies-1.12.2-0.10.189-BETA-universal

I don't know what to say.
