### ISSUE TITLE
Citizen Job Names not Localizing properly

### ISSUE THREAD

**Issue by nick-johnson** [ldtteam/minecolonies#3420]
1.12.2-14.23.5.2815

Most of the names are localizing properly, but the newer ones (crafters I think?) are showing up with the namespace.

![image](https://user-images.githubusercontent.com/1663959/53262772-8592b980-36a5-11e9-8c0c-99f58a21d1c1.png)

**Comment by Raycoms** [comment]
Fixed in newest alpha

**Comment by nick-johnson** [comment]
1.12.2-0.10.188-ALPHA

Latest alpha (as of this morning), job titles still show with namespace and not proper localization and count.

![image](https://user-images.githubusercontent.com/1663959/53289712-8d1a9700-3767-11e9-8fb9-b3cc66741710.png)

**Comment by Raycoms** [comment]
Weird

Am Sa., 23. Feb. 2019 um 14:37 Uhr schrieb nick-johnson <
notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed in the newest version for sure now.
