### ISSUE TITLE
Crash with Storage Drawers' Compacting Drawer

### ISSUE THREAD

**Issue by SanAndreaP** [ldtteam/minecolonies#3443]
### Minecolonies version
Version: 1.12.2-0.10.204-ALPHA

### Expected behavior
I would expect the game not to crash when putting something in a compacting drawer from Storage Drawers

### Actual behaviour
The game crashes with a NullPointerException. I assume it has something to do with this commit: https://github.com/ldtteam/minecolonies/commit/4bb3f638f10142fee0a7ed1fd63296afb5331045

### Steps to reproduce the problem
1. Have minecolonies and Storage Drawers installed
2. place a Compacting Drawer
3. try to right-click it with a stack of iron ingots of any size
4. Game crashes

Here's the complete log: https://gist.github.com/SanAndreasP/aad2d0bd1f8a5731c2b2d2346513b962

**Comment by pauloelr** [comment]
I downgraded some version of the mod i it is happening at least since version 
minecolonies-1.12.2-0.10.198-RELEASE-universal.jar, i didn't went further than that so i can't exactly tell in which version the bug started, it could also be related to the version of Storage Drawers

**Comment by Asherslab** [comment]
Hi there, after looking at the logs and code:
https://github.com/ldtteam/minecolonies/blob/fa8113836b9e5cbbffa094dac4f25c9b6aa4617d/src/main/java/com/minecolonies/coremod/util/TownHallRecipe.java#L67

https://github.com/jaquadro/StorageDrawers/blob/cfa3d185816ad27e21af29e08319d183bc37db25/src/com/jaquadro/minecraft/storagedrawers/util/CompactingHelper.java#L166

it would seem that StorageDrawers (i cannot confirm this) is either providing a null `InventoryCrafting` object (not likely), or the `eventHandler` object inside the previous object is null (most likely), either way, this would be an error on StorageDrawer's part (AFAIK) and not ours. 

@Raycoms would you agree?

P.S. I love clay soldiers, that's all. 

EDIT: well it appears i was half right, but all is good the issue seems to have been fixed =D

**Comment by Asherslab** [comment]
reopening this issue in light of #845

**Comment by Asherslab** [comment]
whoops, that was wrong

**Comment by McKitten** [comment]
Not sure if this helps https://pastebin.com/YmBmWPHg

It is rumoured to be fixed with new alpha's but there is no 'release' yet. Please attend to this. <3

**Comment by Raycoms** [comment]
It's fixed already, we'll make a new release soon

**Comment by Retovath** [comment]
is this fix released?

**Comment by Raycoms** [comment]
yes

Am So., 21. Apr. 2019 um 05:31 Uhr schrieb Retovath <
notifications@github.com>:

**Comment by Fastjur** [comment]
I still have the same issue in the modpack `All The Mods 3`: https://pastebin.com/HwHDsCd8

Connected issue at storage drawers repo: https://github.com/jaquadro/StorageDrawers/issues/697

**Comment by Asherslab** [comment]
@Fastjur you're using an older version of our mod. even older than the version used in this issue.
you need to update to receive the fix

**Comment by Fastjur** [comment]
Ah I only checked the storage drawers mod version, my bad. It's in a mod
pack, I'll see if I can update it without issues. Thanks!

**Comment by Asherslab** [comment]
@Fastjur ATM3 updates the minecolonies version extremely slowly, you may have to update it manually.

**Comment by Fastjur** [comment]
Yes that is what I meant. I'll try that. Thanks :)

**Comment by Fastjur** [comment]
Manually updating did indeed fix the issue. Thanks :)
