### ISSUE TITLE
Miners wont mine (all) the ores.

### ISSUE THREAD

**Issue by Tenshi-JKL** [ldtteam/minecolonies#3726]
I don't know if this is a bug or it is intended to be these way (in which case I dont understand why).
Thanks for your help in advance.
And sorry for my english, it's my second language
### Minecolonies version

Version: 1.12.2-0.10.259-RELEASE

### Expected behavior

- The miner mines every ore that he/she sees and then, if needed, put cobblestone in the hole left.

### Actual behaviour

- The miner sees ores and replaces them with cobblestone (She just puts cobblestone where the ores are, making them disappear). She does this only with the ones on the floors and walls of the mine.

*Miner sees ores*
![2019-07-16_15 22 00](https://user-images.githubusercontent.com/52974290/61319473-a9ce6e80-a7dd-11e9-8837-045067d549fa.png)
*Miner puts cobblestone where the ores were*
![2019-07-16_15 22 24](https://user-images.githubusercontent.com/52974290/61319489-b4890380-a7dd-11e9-9801-3819a44cc140.png)
*Miner does not get any ore*
![2019-07-16_15 24 48](https://user-images.githubusercontent.com/52974290/61319574-e13d1b00-a7dd-11e9-9b02-e8f90e799a1d.png)

### Steps to reproduce the problem

1. Build the miner hut as normal.
2. Let the minor work until he start making nodes.
3. When making the nodes the bug happens.
4.In consequence the mine produces Way less than it could.

**Comment by Raycoms** [comment]
Ohh, I think I fixed this, can you test this in a recent alpha?

**Comment by Tenshi-JKL** [comment]
She still does not mine them but now she gets them in her inventori after replacing them, which is nice. thanks for your help.
After all i think i've been looking at it the wrong way, it's my first time trying minecolonies and I wanted them to do all the job, but I suppose I still have to give them iron and stuff.
Again, thanks for replying so fast.

**Comment by Raycoms** [comment]
yeah she gets them when replacing (the one in the ceiling and floor)
