### ISSUE TITLE
Crash with Ancien Tome

### ISSUE THREAD

**Issue by ZRunner** [ldtteam/minecolonies#3801]
### Minecolonies version

Version: 1.12.2-0.10.344-ALPHA

### Expected behavior

- Well the game shouldn't crash when the Ancien Tome is on the ground.

### Actual behaviour

- I killed a barbarian chief, and when he dropped his old book the game crashed. I can't join anymore the party without crashing because of this book

- Then I did some tests on a new map with the same MineColonies version plus VanillaFix and Optifine, to get more details on it. It seems that I can't take the book in my inventory, no matter if it's from a /give or from the creative inventory.

First crash report (with lots of mods) can be found here: https://paste.dimdev.org/cihuteqaji.mccrash
Second one with only a few ones: https://paste.dimdev.org/legumuweqo.mccrash

### Steps to reproduce the problem

1. Get a map with the latest MineColonies version
2. Pick an Ancien Tome, from creative tab or a loot or /give
3. Enjoy the crash

**Comment by Raycoms** [comment]
fix pushed

**Comment by dhannyjsb** [comment]
I Still have this Issues
https://pastebin.com/hGPFC4ft
using minecolonies-1.12.2-0.10.348-RELEASE-universal.jar

**Comment by Raycoms** [comment]
push fixed
