### ISSUE TITLE
Ticking Entity Crashing

### ISSUE THREAD

**Issue by Chezumi** [ldtteam/minecolonies#3838]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.259-RELEASE-universal / on Enigmatica 2

### Expected behavior

One of my builders happily making the stonemason upgrade.

### Actual behaviour

About 30 seconds or less into entering the game, it just stops working and crashes. One of my builders causes a huge spam rush of ticks that ends with the game not being able to handle it.

[Crash Report](https://justpaste.it/253z7)

### Steps to reproduce the problem

1. Have a colony with a stonemason upgrading to ... level 3 I think
2. Get your builder to do the upgrade
3. End up stuck in a crash loop because RICHARD (the name of the problematic builder) decides to entity tick forever
4. ... Profit

_Note: I've tried some of the tips from previous issues with crashes, like removing FoamFix and going back to a prior colony backup, but to no avail._

**Comment by Talyda** [comment]
Suggest updating your version of minecolonies - it's nearly 100 versions behind, and there's a good chance the problem has been fixed in that time.

**Comment by Chezumi** [comment]
> Suggest updating your version of minecolonies - it's nearly 100 versions behind, and there's a good chance the problem has been fixed in that time.

Honestly I had no idea it was so far behind, it was part of a modpack so I didn't closely inspect the versions of all of the mods within. Thank you for letting me know, I'll confirm if it's fixed things once I've loaded it up!

**Comment by Chezumi** [comment]
Sadly, upon changing the mod to the newest non alpha version, it's still having the same error. I'm going to try and roll back once more to stop the looping but I'm pretty sad it didn't work as I'd hoped.

**Comment by someaddons** [comment]
seems it is related to the request-system, cleaning it up may help: try this command: 
/mc rs reset colony: 1    (replace 1 with your colony ID, can be found with /mc whereami )

**Comment by Raycoms** [comment]
You can a recipe which is cycling in the system, do as someaddons said and
try to check your recipes if there is a cycle (coal to coal block, coal
block to coal for example)

Am Fr., 13. Sept. 2019 um 07:07 Uhr schrieb someaddons <
notifications@github.com>:

**Comment by Chezumi** [comment]
Thank you all for your help! I managed to get into the crafting request my builder was putting through just before the cycle and managed to cut it out. It was a spruce fence of all things, no idea how that managed to get stuck, but now everything is moving back as it should.
