### ISSUE TITLE
ancient tome crash

### ISSUE THREAD

**Issue by anthonyispenguin** [ldtteam/minecolonies#3845]
[crash-2019-09-13_22.21.15-server.txt](https://github.com/ldtteam/minecolonies/files/3612300/crash-2019-09-13_22.21.15-server.txt)

### Minecolonies version

Version: **1.14.4-0.10.358-ALPHA-universal**

### Expected behavior

**ancient tome, no recipe, just looking**
- 
**Upon entering into inventory from creative menus, once on hotbar, crashed game** 
### Actual behaviour

Meshed, and has textures, so no issue, until obtaining
- 
crashes game when placed in inventory, 

### Steps to reproduce the problem

1.  start any world in creative
2. open menu for minecolonies tab for blocks
3. insert ancient tome into hotbar
4. game crash
[crash-2019-09-13_22.21.15-server.txt](https://github.com/ldtteam/minecolonies/files/3612303/crash-2019-09-13_22.21.15-server.txt)

**Comment by Raycoms** [comment]
fixed

**Comment by NielsPilgaard** [comment]
This issue still occurs in `minecolonies-0.10.374-ALPHA`

Crash report: https://gist.github.com/NillerMedDild/37664cf89cffec6f647fa943720a7031

**Comment by Raycoms** [comment]
Can you test the 76?

Am Sa., 21. Sept. 2019 um 06:38 Uhr schrieb Niels Pilgaard Grøndahl <
notifications@github.com>:

**Comment by NielsPilgaard** [comment]
Sure, just a sec.

**Comment by NielsPilgaard** [comment]
[crash-2019-09-21_11.51.11-server.txt](https://github.com/ldtteam/minecolonies/files/3638557/crash-2019-09-21_11.51.11-server.txt)
Yup, it's still an issue I'm afraid.

**Comment by Raycoms** [comment]
Pushed another fix

Am Sa., 21. Sept. 2019 um 06:57 Uhr schrieb Niels Pilgaard Grøndahl <
notifications@github.com>:

**Comment by NielsPilgaard** [comment]
That did the trick, thanks! :D

**Comment by camojackson** [comment]
Still having this issue with the most recent build 1.12.2-0.10.438-RELEASE
[crash-2019-10-18_11.17.33-server.txt](https://github.com/ldtteam/minecolonies/files/3744586/crash-2019-10-18_11.17.33-server.txt)

**Comment by Raycoms** [comment]
Just pushed this second one.

**Comment by camojackson** [comment]
Got it. Thanks!
