### ISSUE TITLE
Male Colonists have no voices

### ISSUE THREAD

**Issue by Raesmal** [ldtteam/minecolonies#3974]
### Minecolonies version

Version: 0.10.348-RELEASE

### Expected behavior

- 
Male colonists are supposed to have some voices, whether that is dependent on job or whatever else, they have voices in other packs or with Minecolonies itself. Females have voices across the board.
### Actual behaviour

- 
The males make no sounds whatsoever, even when you attack them. Female colonists make all the normal sounds from what I can tell, I hear them all the time when talking to females or when they are just wandering around, but haven't heard any from the males. I have mods that modify sounds, so I'm thinking it's a mod conflict going on.

### Steps to reproduce the problem

1.  Add sound mods for ambience.
2.  Place Townhall and wait for colonists to show up.
3.  Bask in the brooding silence all the males seem to be stuck in.
4. ... Profit

**Comment by Raycoms** [comment]
I noticed that a lot of the male workers which are missing their sounds don't play the default male sounds, I fixed this in a recent PR

**Comment by Raesmal** [comment]
I tested the new pre release and the voices are still not there. For both male and female, but females get it when they are builders, but that's what it was before. So, I tested it in it's own pack with no other mods other than structurize and minecolonies, and it was the same for the version I was using in my pack but also the pre release. There's still no male voices or most female voices for that matter. So far, only builder females have voices, but I can't find any other jobs that have them. All in both versions in a solo modpack. Forge Version is forge-1.12.2-14.23.5.2847.
