### ISSUE TITLE
Fisherman goes swimming instead of fishing

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#4143]
### Minecolonies version

Version: 
minecolonies-1.12.2-0.10.592-RELEASE-minimal.jar
structurize-1.12.2-0.10.198-ALPHA.jar
forge-1.12.2-14.23.5.2847-universal.jar

### Expected behavior
Fisherman fishes.

### Actual behaviour
Fisherman goes in the water, come back to his chest and so on.

https://youtu.be/8XQijw5M5iA

The building is medievalbirch level 1. It's built along a river (river biome).

![2019-12-14_18 51 53](https://user-images.githubusercontent.com/2799575/70852632-f361d900-1ea3-11ea-9685-5688fe1bebe7.png)

PS : I forgot to say it was working fine at start.

**Comment by Raycoms** [comment]
Should be fixed now

**Comment by lebanni** [comment]
minecolonies-1.12.2-0.10.612-ALPHA-minimal.jar
Issue still happening. If I fire and rehire him, he works normally for a while, and then start to go in the water.
Here is a list of the mods I have.
http://modlister.com/server/IndustrialScience

Edit : minecolonies-1.12.2-0.10.630-BETA-minimal.jar
Still happening : https://youtu.be/Hp3VmLPxTso

**Comment by miofferg** [comment]
Still happening in minecolonies-0.11.918-BETA-universal
