### ISSUE TITLE
Smelter is unable to interact with furnaces

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4413]
### Minecolonies version

Version: minecolonies-0.10.751-ALPHA-universal
MC - 1.15.2
### Expected behavior

- Smelter is able to fill up fuel and ore into a furnace

### Actual behaviour

- Not able to fill fuel and ore slots

https://youtu.be/6ygUQJFV9sg

### Steps to reproduce the problem

1. Have a smelter with ore and coal inside of their inventory
2. Have a smeltery
3. Nothing happens
4. ... Profit

P.S. - even though, smelter is able to take out the output from the furnaces.

**Comment by Raycoms** [comment]
fixed

**Comment by MineShadow7** [comment]
Unfortunately, the problem still persists in version minecolonies-0.10.753-BETA-universal

**Comment by Raycoms** [comment]
one alpha later

**Comment by Raycoms** [comment]
gotta replace the hut now.
