### ISSUE TITLE
Minecolonies breaks world leaving in Singleplayer

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4605]
Version: 1.15.2:0.11.810-BETA

### Expected behavior
I would expect leaving a world to work basically always.

### Actual behaviour
After some time(in different worlds i seem to have had this happen after 22-~50 hours) a world becones damaged and if you try to leave it the game freezes endlessly(i left it running for 2 hours in this state in the background once), also at that point you can't use commands that need a permission level of over 0 without the Open To Lan trick. everything else seems to work fine.

### Steps to reproduce the problem
1. Play a single player world with cheats enabled for some time(idk on what the time it takes depends)
2. join the world and see commands aren't longer working
3. leave the world and see the game freezing
4. ... Profit?

### Logs: Latest.log and crashlog at https://gist.github.com/
There was no crash, but i can post three latest.log files:
The log from when the world seems to have gotten damaged(seems to contain stuff about datafixers): [latest.log](https://gist.github.com/ToMe25/be97568d9a5e1dc272ce5ab523c1d0a3)
The log from the first time in that world the issues occured: [latest.log](https://pastebin.com/RX11v6gS)
The latest log from that world which is the second with that issue: [latest.log](https://pastebin.com/vvpbnACg)

Note that i don't know for sure whether the world got damaged at the time of creating of the first or second log.
Also note that i had this happen to atleast half of my worlds with Minecolonies and none without.

**Comment by Nightenom** [comment]
I can fix the errors about datafixers, but I see you are trying to upgrade old schematic and then place it - that might be unstable and may actually cause some problems

**Comment by ToMe25** [comment]
I didn't update an old schematic, the world also was only ever used with this exact version of Minecolonies.
I instead placed a schematic in with the paste button in the builder tool gui, broke the hut block and placed it in again(this time with the accept button of the builder tool) to make the structure work, as they just don't work otherwise.
I expected the datafixer stuff to not be that important, but as it starts with [Render thread/ERROR] i was thinking maybe it is.
Also it was just the only anormal thing in any of the logs i could find...

**Comment by ToMe25** [comment]
I also did that with pasting the schematic and editing it previously in this world and it didn't cause any problems, so i am not sure whether that can actually be the problem, additionally i had the same problem in other worlds where i didn't paste in and/or update any structures that way, thats just longer ago and i can't find/cant identify the corresponding logs.

btw: i edited the previous comment to contain more information, but the discord for example wont know about these edits.

**Comment by ToMe25** [comment]
Thanks alot, the new Structurize version doesn't just prevent the issue from happening(i expect it does, but as that isn't reproducible, i am not sure), but it also fixes worlds where this had already happened, which i didn't think was possible like that.

**Comment by Nightenom** [comment]
okaaaay, like I just fixed that errors in datafixers, dumb mojang

**Comment by ToMe25** [comment]
OK it did fix it, but not for long, after playing a bit longer in that world its now broken again...
Edit: it was like the third time of joining where the issue came back...

**Comment by ToMe25** [comment]
ill add some new logs from that world later :)

**Comment by Raycoms** [comment]
None of our other players got issues with world corruption neither do we on the official server, do you have any additional mods?

**Comment by ToMe25** [comment]
i am only using JEI, Minecolonies and Structurize, and i also have some servers that don't have that problem, its just singleplayer and it isn't really the standard corruption as the world is still playable, just commands and leaving don't really work anymore.

**Comment by someaddons** [comment]
and why do you think it is minecolonies related?

**Comment by ToMe25** [comment]
because i never had the problem without it.

**Comment by ToMe25** [comment]
and in like half my worlds with it.

**Comment by someaddons** [comment]
so it might just be rng? :D

**Comment by ToMe25** [comment]
i play enough without minecolonies that i don't believe that :)
Or did you mean from the worlds with minecolonies? that might be it, idk

**Comment by Raycoms** [comment]
If you send us the log of you trying to leave the world and it not working we can check what it is. But from the amount of players etc we have I atm doubt this is related to minecolonies.

**Comment by ToMe25** [comment]
as i said above i will get the logs from with the new structurize version later today, i guess in like an hour or so.

**Comment by ToMe25** [comment]
This is the [latest.log](https://pastebin.com/8AmEF9Q1) from when it last worked with the new structurize version.
Here the [latest.log](https://pastebin.com/VLGWWhyQ) where the leaving didn't work again, after the left the game i gave it half an hour and as it was still saying "saving world"(not sure, but i think that was what it said), i closed the game.
Also i tried to use the /gamemode command somewhere in there, but that doesn't seems to show up in the log.

**Comment by Nightenom** [comment]
The reason for freeze might be minecolonies trying to save something big/cyclic, otherwise no idea

**Comment by Raycoms** [comment]
I can't see anything there @OrionDevelopment any idea?

**Comment by ToMe25** [comment]
btw i just found out that from a previous test in that directory there seems to be a MixinBootstrap-1.0.2 file left in there, that i missed, i hope that doesn't changes it, but i just now noticed it in the log as i really thought i had removed all mods from the mods directory before testing this.

**Comment by someaddons** [comment]
that sounds like a thread not closing and minecraft waiting for it to shutdown

**Comment by ToMe25** [comment]
A few new things:
1. I now figured out how the MixinBootstrap got there, it was a leftover from an earlyer test with phosphor.
2. I have had this issue before and while i can't be a 100% sure i am still pretty sure in that worlds i played without anything that could have used Mixin.
3. removing the MixinBootstrap did solve the Issue, but as updating structurize did that too for a few hours, i don't believe(yet?) that it really did solve it for long.

**Comment by ToMe25** [comment]
It seems to also happen without Mixin, but i haven't found a way to reliably reproduce it, and will stop trying for now.
Also every change to the mod list(updating, adding or removing one or more mods) seems to temporarily fix this issue, but it will always reoccur later.
Also it seems like some worlds event with Minecolonies just aren't affected at all.

**Comment by Raycoms** [comment]
were you able to reproduce this without minecolonies yet?

**Comment by ToMe25** [comment]
no, never.

**Comment by ToMe25** [comment]
i tried this again a few minutes ago, but i couldn't, the problem is i can't reliably reproduce it with minecolonies either, so that doesn't mean that much.

**Comment by marchermans** [comment]
Lets see if it happens again without the mixins.
There is some funkyness in your logs that is for sure.

**Comment by ToMe25** [comment]
It did, thats what i meant by "It seems to also happen without Mixin",
i have also researched some of my old worlds where that happened some more,
and can now safely say that, at the time i played them, didn't use any mods i know of that they use Mixin, the problem is i can't seem to find the logs from back then, and also there may be a mod inside what i used that uses Mixin that i just don't know about.

Edit: This could of coarse also be because of the pre-existing world that was loaded with Mixin previously, but as i can't reliably reproduce this, i can't just make a new world to see whether it will happen again.

**Comment by marchermans** [comment]
Since this is not reproducible, i am going to close the issue.
If @ToMe25 is able to reproduce this. Feel free to reopen the issue.

**Comment by Rexxios** [comment]
I may be late to a fix, but I have @ToMe25's bug as well

**Comment by Raycoms** [comment]
Fixed in the latest

**Comment by Rexxios** [comment]
> 
> 
> Fixed in the latest

When is the latest, because I am using version 13.330 ALPHA
