### ISSUE TITLE
Strange citizen summary list in Town Hall

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4663]
![Jobs issue](https://user-images.githubusercontent.com/63854770/79570150-3386d180-80b9-11ea-8098-51a2e8634249.jpg)
### Minecolonies version
Minecolonies version 0.11.832-ALPHA
Minecraft version 1.15.2
Forge version 3.11.46

### Expected behavior
We should see a correct list of all citizens jobs in town hall summary.

### Actual behaviour
If you look at the screen, you will see some strange namings (are there my knights ?).
There is also a baker however it is written 0/1.
The total does not match the number of citizens.

### Steps to reproduce the problem
1) Wait for the night in order to have the summary recalculated
2) See the errors
3) I tried also to fire all my citizens, and hire them again, wait for the night, still the same.
4) It is like that since many many versions. At least 2 weeks.

**Comment by Raycoms** [comment]
Yeah this part of the code needs a rework to make this work nicely, atm this is not solved very well

**Comment by DiabolosMan** [comment]
ok. No pb. Good luck for the rework

**Comment by DiabolosMan** [comment]
![TownHall - CountMismatch](https://user-images.githubusercontent.com/63854770/79725441-8777fd00-82e9-11ea-80d7-9baa80a8e77c.jpg)
I confirmed that it is a lot better with this new version. There are still some strange values:
0/2 pupils. I have 1 child only. Total count is still strange. Hapiness value is more than 10. I thought it was capped to 10

**Comment by Raycoms** [comment]
What is wrong with the total?

**Comment by Raycoms** [comment]
And the pupils, means you got a school with 2 slots, but no kids studying there, isn't that right?

**Comment by DiabolosMan** [comment]
I have no school yet. I have one children only and 25 citizens. If we add all the numbers in the screen, the total is 24

**Comment by Raycoms** [comment]
fixed it now

**Comment by DiabolosMan** [comment]
It is better…. Still have issues with version 0.11.858-ALPHA

The total number is incorrect so I have -1 for unemployed.

Moreover, since the last two versions, I cannot have new children in my city
I have 3 citizens huts lvl 5, so I can have 15 citizens max
I also have 1 barracks, all towers level 5, so I should have 20 citizens more max
So a maximum of 35 citizens. Maximum is 25 in the screen shot. 
I do not know how I can have more knights as I cannot have more children…. And of course, I cannot assign new citizens to tower guards
![BugTownHallRecap](https://user-images.githubusercontent.com/63854770/79866530-38ab8f80-83dd-11ea-9adf-b275aba3a966.jpg)

**Comment by Raycoms** [comment]
can you send me this world?

**Comment by DiabolosMan** [comment]
It will be huge. What do you need ? Minecolonies folders ? Server side ? Client side ? Chunks ?

**Comment by Raycoms** [comment]
just the world folder, if you could prune some far out regions that'd be nice

**Comment by DiabolosMan** [comment]
Compressed: 700Mo. I am not the owner of the server. So I can ask the admin to give me a region. But don't you need a minecolonies folder ?

**Comment by Raycoms** [comment]
700MB is fine, I got 4gb worlds already =P No, I need only the world folder

**Comment by DiabolosMan** [comment]
OK. Perfect. I will send you. Is it possible to contact you private in order not to put the world everywhere online ?

**Comment by Raycoms** [comment]
yeah, you can pm me on our discord

**Comment by DiabolosMan** [comment]
@Raycoms, where you able to find the reason ? On my server, I am still stuck and cannot have more citizens

**Comment by Raycoms** [comment]
Do you have the research unlocked for this already?

**Comment by DiabolosMan** [comment]
You mean that it was a change added recently ? 
Because I built barrack lvl5 with all towers, and I had exactly one free space to have new citizen. I waited some time to have a new child then him grow up. I was full. I assigned it to the barrack and again, I had one new free space. I did this process for 2 or 3 days until I reach the number in the screen shot. So it means at the screen shot time, when I upgraded to a new minecolony version a research is now mandatory to have this behavior again ? What is this research name ?

However, I still have the -1 for unemployed. Is it for the reason ?

**Comment by Raycoms** [comment]
yes, it was a change added recently

**Comment by Raycoms** [comment]
It's in the 2nd branch

**Comment by DiabolosMan** [comment]
I have found why I was locked. It is a bug. I had one citizen that was assigned as a Knight AND also as a Composter. So this is why I had -1 I think for unemployed. So I fired the citizen from both roles, and hired him again as a Composter. Since, everything is working perfect.

So in fact the bug is: How was it possible that the same citizen was assigned 2 différents jobs (I have some building with manual hiring)

**Comment by Raycoms** [comment]
That is very weird. That should not be possible yes.

**Comment by Raycoms** [comment]
If you find a way to reproduce it please open a new issue with that.

**Comment by DiabolosMan** [comment]
ok. If it happens again, I will open a new issue
