### ISSUE TITLE
Resources disappearing for Builder

### ISSUE THREAD

**Issue by Rayzerfang** [ldtteam/minecolonies#4905]
I have run into this issue multiple times across multiple builds and modpacks. Builder's Hut items needed for a build will show what is needed. After I fulfill all desired requests, items begin disappearing from it randomly as if builder is using them but they simply disappear from all inventories as if they never existed. Today for example, builder was building citizen hut and it showed he needed 2 white beds. I placed them in the inventory by clicking the up-tick arrow where items are requested and it goes turns black showing fulfilled then they are removed and shows he still needs them.

**Comment by sjstark** [comment]
I'm also having this issue, I play on a Valhelsia 2 server and the server had an update pushed this week. After the update I started having my resources constantly disappear after I give them to the builder. At first I thought it was an issue with the Delivery Man snagging things before the builder could use them, but I disabled the delivery man and it's still happening. I've checked for the resources in my warehouse, in villager inventories, in hut inventories, and it just seems like it's getting deleted entirely.

**Comment by sjstark** [comment]
Sorry, I can't produce more information on what seems to be causing it, I know that's the best way to help. Right now, I have (2) builders, one level 4 and one level 2 and a delivery man (as well as other citizens but those seem to be the ones interacting with each other). Delivery level is set to automatic, though I have tried changing to manual and setting to different levels to see if that helped.

I'm trying to currently upgrade my university to a level 2 with the level 2 builder's hut and she keeps "losing" the supplies. I was trying to upgrade a citizen hut to level 3 with the level 4 builder and he was doing the same thing. I eventually just got op-ed on the server and gave myself the materials they were losing to power through it. They had space in both character inventory and hut inventory when I tried to give them supplies.

I've had this happen in the past as well and don't recall what I was working on to recreate it.

**Comment by sjstark** [comment]
Hey again, caught the glitch happening on a record. Figured I'd upload to share if it helps at all:
https://youtu.be/q-MtgeydbQ4

**Comment by sjstark** [comment]
Hey Raycoms, responding to your question on the other thread that you closed for this one. I'll keep an eye out for future instances, but in the video on #4923 thread, it looks like the counts for the total materials don't increase, the number in inventory just decreases and the number needed increases. 

I'll definitely keep an eye out for other cases though (one happened today but i didn't screen record it in time, but I believe it's as described above) I'll also push for our server to update to latest minecolonies version, just hard to keep up sometimes with you guys working so fast!

**Comment by sjstark** [comment]
Happened again,

The materials truly seem to disappear. I ran around the entire colony after this video and didn't find 2 stacks worth of oak stairs anywhere (nor the other items)

https://www.youtube.com/watch?v=ejJy0Q3RK0M&feature=youtu.be

latest.log from that time: https://gist.github.com/sjstark/b991bdb850d058a2d0f710cc49c3e181

ONCE AGAIN: haven't updated the server to the latest version of minecolonies yet, not sure if that'll help with the fix or not.

**Comment by Pixelmnkey** [comment]
Having the same issue, any update?

**Comment by Raycoms** [comment]
Up to now, none of us were able to reproduce this in any way, since this only seems to occur randomly. Even on our let's play with the devs server that did never happen up to now.

**Comment by Raycoms** [comment]
Wondering if some kind of mod causes this.

**Comment by Pixelmnkey** [comment]
I'm using vallhelsia no idea what could cause that.

**Comment by Raycoms** [comment]
Could you try something and remove like all chests/barrels/furnaces/signs/banners from the builder hut (you can keep the racks) and check if it still occurs?

**Comment by Pixelmnkey** [comment]
It only has one rack and the hub, it's the t2 asian.

**Comment by Raycoms** [comment]
then, let's check if you destroy the rack then if it works.

**Comment by Pixelmnkey** [comment]
It seems fixed now, tried removing the furnace and updating forge aswell, fingers crossed! Thanks :)

**Comment by pa1nki113r** [comment]
Still having this issue too. It's super frustrating and I have absolutely no clue how to replicate it. Going through all that effort gathering resources then having your builder somehow "lose" the object is ridiculous.

**Comment by pa1nki113r** [comment]
It's weird. I almost think there's a desync or something going on with the client and the server when transferring items to a hut's storage. I wonder if its conflicting with one of my other mods that handles player updates such as Journeymap (1.15.2)

**Comment by thenders11** [comment]
So far, removing the racks from my level 2 builder's hut has fixed this for me. Items started disappearing after I upgraded to a t2 builder, and it was happening on every new building. I'm on a 1.15.2 Valhelsia 2 server using all Asian buildings.

**Comment by pa1nki113r** [comment]
Just updated to the latest version, the issue is still happening.

**Comment by pa1nki113r** [comment]
Had to resort to just cheating on my survival server at this point.

**Comment by Raycoms** [comment]
I have an idea what might be causing it and I'll look into it.

**Comment by thenders11** [comment]
It started happening to me again after building a warehouse and delivery hut. I don't even have a citizen working as a deliveryman though, the job is empty.

**Comment by Spray-Art-Rick** [comment]
I've been experiencing this same problem for several versions now. I've tried giving the materials directly to the builder, putting them in racks available in the building, using the arrow to see the material listing and submitting them there or putting them in the inventory of the building's controller block. After initially accepting the requested materials a few minutes later I'll find the builder stopped and requesting the materials again. All materials have vanished from the buildings inventories.

Not sure if it helps, but I've noticed that if I use the arrow to submit the materials one at a time I can never find those materials in any of the storage locations within that building after they've been accepted. 

I would say that for every 10 times I fill out a builder's request list (using any of the methods) the items disappear more than half the time.  It's pretty much forced me into dropping into creative mode and resubmitting them when they disappear.

**Comment by MaxAstro** [comment]
I'm playing Valhesia 2 and definitely having this same problem.  I needed three citizen huts, so I very carefully loaded the builder's hut inventory up with three times the required items for one.  After finishing the first hut, the builder suddenly doesn't even have enough resources to finish the second.

**Comment by nephilese** [comment]
I can attest to this occurring on my current Valhelsia2 modpack server.

**Comment by MightyLuu** [comment]
I have the same problem on my server running forge-1.15.2-31.2.30 and structurize-0.13.8-ALPHA / minecolonies-0.13.34-ALPHA (latest alpha at this time). 

Additional mods are Dynmap-3.0.1 and TerraForged-1.15.2-0.1.0-BETA-2 - but i these are just for map rendering and world generation, i dont think they cause problems with minecolonies.

Doesn't matter if the resources are given via the builders requests UI or the hut UI, some items just vanish. To build a building the builder needs 3 to 4 times the resources -and constant attention by the player to fill the resources up again.

Even when the hut shows all needed resources are there, a few seconds after filling it, the items are gone and the builder requests them again.

**Comment by Raycoms** [comment]
you only got those additional mods, no others?

**Comment by MightyLuu** [comment]
no other mods

**Comment by Raycoms** [comment]
which other mods?

**Comment by MightyLuu** [comment]
none :D sorry for the confusion - only dynmap, terraforged and minecolonies

thanks for the fast reply btw

**Comment by Raycoms** [comment]
Ah, okay, sorry, yes. That's very weird. Are you able to reproduce this in singleplayer or on a local server easily?

**Comment by MightyLuu** [comment]
no problems in singleplayer maps with these mods and config, might be desync on the server?
but the connection seems fine, no lags or other problems so far.

**Comment by Raycoms** [comment]
Do you have a dimension mod or so?

**Comment by MightyLuu** [comment]
nope no mods

so i tested some stuff:

1. server restart
2. cleared all racks and put the items directly into them, he didnt recognize them.
3. items given via builer/hut UI vanish
4. server restart
5. tried to put then in via the hut UI, the UI shows its fine, but the items didnt leave my inventory (survival), 2 seconds later the  hut shows it needs the resources. (thats good, this time the items dont disappear)
7. also the racks look like they have items (from the outside), but i cant see any items in them - so maybe a visual bug and the racks are full and i cant put resources in)
8. server restart
9. racks look empty now, i can give items via the hut UI ... and they stay there.

so it seems fixed by clearing all the racks and restart the server.
but i did restarts before and still had issues, so i dont know what was wrong and what really fixed it

**Comment by Raycoms** [comment]
If you destroy all racks, does it still happen?

**Comment by MightyLuu** [comment]
ill try that if it happens again, for now its working fine

**Comment by MightyLuu** [comment]
ok i found the explanation for the problem of loosing some resources when updating the builders hut itself, he breaks the rack on the top floor  (spruce medival 4 to 5) he then looses the items stored there. (maybe there is a way to force the builder to take out all items before breaking a chest/rack?)

what happened while building other buildings, idk, might be a combination of bugs/server desync

**Comment by MightyLuu** [comment]
resources still are getting lost sometimes, now on version 0.13.43-ALPHA.
looks like it happens if more than one kind of item are given via the hut UI in a short time.
like using creative and just klicking on everything on the list. This way it fails very often.

On the other hand, when put in one by one, sometimes it takes a moment for the UI to display it correctly but it woks most of the time.

I dont think its server lag/desync, everything else runs just fine on the server

**Comment by MightyLuu** [comment]
still happens randomly in 0.13.61-ALPHA.
It seems like the resources are registered by the builder UI. But they dont end up in his racks/inventory.

What happens:

1. builder has 112/244 shingles.
2. I give all needed resources via the hut UI.
3. The UI showed 244/244 shingles.
![builderUI](https://user-images.githubusercontent.com/46848677/88339306-1c035880-cd3a-11ea-8ccd-8a0f0f772012.PNG)
4. I checked all his racks/inventory/hutblock and i only found 112 shingles.
5. A minute later the UI shows 112/244.
![builderUI2](https://user-images.githubusercontent.com/46848677/88339431-4fde7e00-cd3a-11ea-9f6e-6148e036bc7e.PNG)

Edit:
tried it again (in creative) just klickend down the list of all needed resources and the bug happened again.
- UI shows 244/244 shingles
- checked all his racks/inventory/hutblock - found 21 additional shingles in his inventory
- Seconds later the UI shows 133/244 - the 21 shingles got added - but 111 are lost again.

the shingles are just an example because i was able to track their numbers easily, other items disappeared just like them.
it's still confusing and hard to test because it happens only sometimes

**Comment by jhbr** [comment]
Same behaviour for me, unfortunatelly is almost impossible to find out when it happens. I tried:
- fullfilling the requests of the builder
- fullfilling the requests of the builder's hut
- storing the items directly into the builder's hut chest
- storing the items directly into the builder's inventory

Happened in all cases

**Comment by Raycoms** [comment]
Can you also check if that happens with the newest version too? 72?

**Comment by Raycoms** [comment]
Btw, blocks like signs, torches, rails, carpet and ladders don't count since those can be destroyted by accident in the build process

**Comment by Aalandriel** [comment]
I'm seeing this also on The Seilican Experience modpack (not on newest minecolonies version). I'm playing on the server, so can't upgrade minecolonies. Asked Kree to update when he has time.

I noticed items/blocks going missing from all worker huts and my fisherman started complaining about full inventory, but the hut inventory showed empty. My chickenherder wasn't producing anything so I thought the hut might be glitched on the current version so decided to tear it down. When I destroyed the hut block all the missing items dropped. I then went to the fisherman and destroyed its worker hut block and all the items that were clogging up the system dropped.

It's as if the hut inventory becomes invisible/enters the void, but it does not appear to be truly lost as you get the stuff back when destroying the hiut block. Only then you need to rebuild your hut from scratch.

**Comment by Beralath** [comment]
Got some issue on Valhelsia 2. Suddenly my colonists decided items should disappear.
All the resources they were bringing back to their hut just evaporated in the air. I could see them in their backpack the second before though. Server restart helped to fix but a few hours later it happened again. Solved by restarting the server during the night later on.
It impacted the whole colony both times. Racks were looking full, but nothing when opening them.

**Comment by Raycoms** [comment]
I'd like to know if this is fixed with the latest.

**Comment by Beralath** [comment]
Just checked, I'm playing with the latest v. of Valhelsia 2, they have this file :
minecolonies-0.13.78-ALPHA-universal.jar

So obviously not the latest.

**Comment by MightyLuu** [comment]
From a few test, it looks like it depends on forge?
This time i tested version 31.2.36 and now i cant reproduce the bug. 
I installed a new server with the new forge version and started a new map, had no problems yet.
With forge 31.2.30 and 31.2.33 i had this bug several times over similar test periods.

**Comment by Aalandriel** [comment]
Looks indeed to be fixed. Tested using 13.106 Beta and Forge 31.2.36

**Comment by Aalandriel** [comment]
Spoke too soon. Now seeing the issue again. It appears that you can temporarily fix this by breaking the building block and building again.

**Comment by Raycoms** [comment]
It's fixed now int he newest newest.

**Comment by Spazmunki13** [comment]
I seem to be having this issue, although it happens when I put things into the Builder Hut inventory.

**Comment by MotionlessTrain** [comment]
Check if the inventory of the builder’s hut and the racks is not full. Giving the resources would then fail, and they are given back to you instead.

**Comment by Spazmunki13** [comment]
The inventory wasn't full and it didn't come back into my inventory.
