### ISSUE TITLE
Healer should keep potatoes and carrot for healing instead of eating them when hungry

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4979]
### Minecolonies version

Minecolonies version 0.11.940-ALPHA
Minecraft version 1.15.2
Forge version 3.11.78

### Expected behavior
Healer should keep carrots and potatoes when hungry, in order to heal.

### Actual behaviour
When hungry, it eats carrots and potato so always asking for carrot and potato.
Moreover, If it has other food, it starts eating carrot and potato.

**Comment by SirSmuggler** [comment]
Likewise for the builder. I had him upgrade a fishermans hut and he needed a tropical fish for it. I managed to snag one for him and he started to walk to the build site, but ofcource he got hungry on the way and eate the damn thing.

**Comment by Ampaex** [comment]
This issue should be fixed by this commit #5011.

**Comment by DiabolosMan** [comment]
It is still not fixed in minecolonies-1.15.2-0.11.949-universal-universal. Is it supposed to be fixed in this version ?

**Comment by DiabolosMan** [comment]
Still occurs in minecolonies-1.15.2-0.11.958-universal.jar. I also noticed it for the fisherman that ate the so rare PufferFish I was looking for.

**Comment by Raycoms** [comment]
The healer shouldn't eat those anymore. However, the pufferfish is normal.
