### ISSUE TITLE
Blacksmith doesn't do anything, does not leave home for work.

### ISSUE THREAD

**Issue by staviq** [ldtteam/minecolonies#4983]
minecolonies-0.11.944-ALPHA-universal

Blackmisth is stuck with Current Activity: START_WORKING.

He does not leave home.

If i recall him to his workplace he just stands there, or goes back home, and does not come back the next day.

There are open requests for swords and tools that the blacksmith has in his patterns and he is the only one capable of crafting those.

Blacksmith himsef has no requests.

EDIT: Other villagers from the same house are leaving in the morning fine, and it's not raining.

**Comment by SCBionicle** [comment]
Is the player marked as the resolver?

**Comment by staviq** [comment]
How do i check that ?

This is what i get:

https://i.imgur.com/A1Dg12L.png

**Comment by Raycoms** [comment]
in the clipboard, does the request appear?

**Comment by SCBionicle** [comment]
Mine colonies has a clip board item you can craft that shows all open requests that can’t be resolved by the colonists themselves. See if they should in that. Sent from Mail for Windows 10 From: staviqSent: Wednesday, May 13, 2020 3:48 PMTo: ldtteam/minecoloniesCc: Seth; CommentSubject: Re: [ldtteam/minecolonies] Blacksmith doesn't do anything, does not leave home for work. (#4983) How do i check that ?This is what i get:https://i.imgur.com/A1Dg12L.png—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by staviq** [comment]
No, no related requests in the clipboard, as i said in the bugreport, blackmith has no requests.

EDIT: Also, i gave him manually any possible material that he might need and he still does nothing.

The weirdest part is that he does not even try to leave his home.

**Comment by Raycoms** [comment]
I mean, is the swrd, armur, tool request in the clipbard?

**Comment by staviq** [comment]
Oh, you mean the other way around, yes, there are some requests for swords.

**Comment by SCBionicle** [comment]
It's possible that the crafter doesn't have the necessary materials in the
warehouse. Are there materials in the warehouse that is required to craft
those items?

**Comment by Raycoms** [comment]
If you request something in the psotbox, will the crafter d this?

**Comment by staviq** [comment]
I think i know what is going on.

I just found my whole village starving to death in the restaurant.

Deliverymen are going back and forth "checking" inventories of buildings, taking nothing from them, and bringing this "nothing" back to the warehouse.

This leads to a situation where the whole supply chain stopped working, deliverymen are hungry and they pile up athe the restaurant that is waiting for food to be delivered, but it won't because deliverymen are busy transporting air.

**Comment by staviq** [comment]
Btw, what's happening to the wiki ?
I just tried to look up how to reset request system and the wiki is down.

**Comment by Raycoms** [comment]
Alternative  instance: https://ldtteam.github.io/MinecoloniesWiki/

Can you send me that world?

**Comment by Raycoms** [comment]
Preferably before resetting the system and fixing it

**Comment by staviq** [comment]
Sure, i just have really shitty internet connection, ill have to do this from work tomorrow.

**Comment by Raycoms** [comment]
great

**Comment by staviq** [comment]
https://drive.google.com/file/d/1Pr8Q4E2llK_jPdQX-HejooI-tSh8Pwqr/view?usp=sharing

**Comment by Raycoms** [comment]
OKay I debugged the world, yes it seems like the entire colony halted because the cook got hungry too and there was no food in the restaurant by then =D
