### ISSUE TITLE
Miner doesn't mine all available ores

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5240]
minecolonies-1.15.2-0.11.960-universal.jar
structurize-0.10.324-ALPHA.jar

The miner doesn't collect ores on the sides, floor and ceiling, as he used to do.

![2020-06-17_03 53 34](https://user-images.githubusercontent.com/2799575/84846191-8e538f80-b04e-11ea-93e5-f1ad618b3b32.png)

**Comment by Asherslab** [comment]
Was fixed in the latest versions, please look at some newly created tunnels as those tunnels may be old

**Comment by lebanni** [comment]
This tunnel was done in the version I mentionned. I'll wait for the next version.

**Comment by Mekle001** [comment]
I just upgraded to 11.960, and followed the miner around for several nodes. I'm still seeing the behavior pictured above.

**Comment by Raycoms** [comment]
That's weird, I gotta check into it again then.
