### ISSUE TITLE
Cannot build Guard Tower

### ISSUE THREAD

**Issue by PoliteDevil** [ldtteam/minecolonies#5674]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: Bug is featured in 0.13.183 up to 0.13.190 (lastest at this time)
- Structurize Version: 0.13.50
- Related Mods and their Versions: N/A

## Expected behavior

Place the Guard Tower with the building tool, then builders build them.

## Actual behavior

Placing the Guard Tower with the Building Tool, then right-click on the Guard Tower and "This block is missing its respective building, try restarting or loading a backup!" is written _twice_ in the chat. I noticed that the Guard Tower item is **not** removed from the inventory, and you can break the one on the ground to gain one free Guard Tower, but this only happens when using the Building Tool. When you place the block without the Building Tool, the text mentionned above only appear once instead of twice and the block is removed from your inventory. The problem also happens in creative mode.

## Steps to reproduce the issue

1. Place Guard Tower using the Building Tool
2. Right-click on said Guard Tower
3. Look at the chat
4. Don't profit?

### Logs

The issue does not lead to a crash, so no file is available.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
are you within an existing colony area?

**Comment by PoliteDevil** [comment]
> are you within an existing colony area?

Yes, about 10-15 blocks from the border.

There's all these threads on Discord: 
https://discordapp.com/channels/139070364159311872/741531816422539384/749268576128466957
https://discordapp.com/channels/139070364159311872/741531022872674314/748911549757915138
https://discordapp.com/channels/139070364159311872/741531022872674314/749054864159670372

**Comment by Raycoms** [comment]
Fixed in newest

**Comment by akobryan1** [comment]
> Fixed in newest

The error still occurs. I am using minecolonies 270 and structurize 66 on 1.16.2

I'm not using any other mods. Barracks and Barracks tower show the same error as well.

**Comment by PoliteDevil** [comment]
> > Fixed in newest
> 
> The error still occurs. I am using minecolonies 270 and structurize 66 on 1.16.2
> 
> I'm not using any other mods. Barracks and Barracks tower show the same error as well.

Are you sure you're using the lastest version of Forge? That's what caused the issue.

**Comment by akobryan1** [comment]
> > > Fixed in newest
> > 
> > 
> > The error still occurs. I am using minecolonies 270 and structurize 66 on 1.16.2
> > I'm not using any other mods. Barracks and Barracks tower show the same error as well.
> 
> Are you sure you're using the lastest version of Forge? That's what caused the issue.

It works now, thank you

**Comment by SpedHazo** [comment]
How do i update my forge to the newest on CurseForge? (playing ATM8)
