### ISSUE TITLE
Citizen AI Crash

### ISSUE THREAD

**Issue by BinaryConstruct** [ldtteam/minecolonies#6188]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: minecolonies-0.13.488-ALPHA-universal.jar
- Structurize Version: structurize-0.13.100-RELEASE-universal.jar
- Related Mods and their Versions: ATM 6 pack (with optifine)

## Expected behavior
Builder AI should work assigned jobs or jobs in range.

## Actual behavior
Builder AI crashing frequently, after fire/hire or pause/reset AI will crash again and fail to pick up jobs.  
`/minecolonies colony requestsystem-reset-all` also does not resolve the issue.

![image](https://user-images.githubusercontent.com/456755/100964049-66b58e00-34ed-11eb-9d25-ad0bfccab4e1.png)

## Steps to reproduce the issue

Large colony, 50+ workers with 3 builders, 10 couriers at max level, misc. worker builders such as sawmill, etc.

Manually assign builder to building outside of range, builder AI will continuously crash even after all build requests are cancelled in town hall.

I'm not sure if this will reproduce in all cases, but I believe this is what instigated the issue in my world.

### Logs

https://gist.github.com/BinaryConstruct/4f8ec774a1c2eb08c4586c43d37c0bec

### Notes

Colony has been working normally for several weeks before this (with this pack).

Rolling back to version 0.13.47x, the builder does not give the popup crash message but the builder fails to pick up jobs or move. They will continue to go to house and sleep at night, pick up food and eat but will never pick up build orders.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
can't reproduce this, and also your error log is from the 486 version not the 488 like you said here, so update and try again?

**Comment by BinaryConstruct** [comment]
Same issue with 486/488, I was trying multiple versions to see if I anything was different. Rolling back the world save did cause the issue to stop reoccurring. Perhaps something like a command to reset all build orders would help?

**Comment by someaddons** [comment]
fixed

**Comment by BinaryConstruct** [comment]
I'm still having the AI crashed popup, but once I click the "tell me later" button they go about working as normal. However, now my miner is wandering into the ocean above the mine tunnels

![image](https://user-images.githubusercontent.com/456755/101289444-19be0a00-37c2-11eb-91ed-f3f3b98707e2.png)

**Comment by Raycoms** [comment]
that can happen when one of their tunnels is blocked

**Comment by BinaryConstruct** [comment]
It looks like the issues with AI errors are still occuring occasionally. However, they start working now when clicking "this is the best I can do" ignore or "tell me later" so it is much improved. Thanks for the fix.
