### ISSUE TITLE
Cant use tabs of workers/buildings

### ISSUE THREAD

**Issue by nevth** [ldtteam/minecolonies#6886]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.68-ALPHA-universal
- Structurize Version: structurize-0.13.148-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Want to change fuel items, select them in window

## Actual behavior

Windows is empty.
![2021-04-08_18 12 47](https://user-images.githubusercontent.com/80281524/114061104-572cc400-9896-11eb-8911-e5deb62ee000.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in the latest alpha

**Comment by nevth** [comment]
which would that be? with 92 it still persists, after one restart of the server

**Comment by Raycoms** [comment]
What UI scale are you on?

**Comment by nevth** [comment]
3, i tried all from 1-6 and auto, still the same issue now on 93

**Comment by Raycoms** [comment]
singleplayer/multiplayer? Can I get your client startup log?

**Comment by nevth** [comment]
multiplayer
[latest.log](https://github.com/ldtteam/minecolonies/files/6287755/latest.log)

**Comment by Raycoms** [comment]
can you try without optifine?
