### ISSUE TITLE
Mirroring of barracks tower placeholder doesn't work

### ISSUE THREAD

**Issue by dhouck** [ldtteam/minecolonies#7212]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.210-alpha
- Structurize Version: 0.13.177-alpha
- Related Mods and their Versions:

## Expected behavior

When you place a structure with a barracks tower placeholder (eg. medieval birch alternative barracks) mirrored, the barracks tower hut blocks will be in the correct mirrored state, and the barracks tower will be built mirrored.

## Actual behavior

Rotation works, but preview shows the barracks tower placeholder in the wrong orientation, and actually building the barracks tower puts it in unmirrored.

## Steps to reproduce the issue

1. Grab a barracks hut block and begin placing it in a style that has barracks towers inside
2. Find a barracks tower in the preview and observe its orientation.  Mirror the barracks.
3. Find the corresponding barracks tower hut block and observe that it is in a different orientation relative to the rest of the structure
4. Build the barracks mirrored
5. Attempt to build the barracks tower.  Notice the construction tape is in the wrong location.

### Logs

- latest.log: Unlike the other issues I'm uploading now, this does show up a bit in latest.log, but I think not usefully.  https://gist.github.com/dhouck/ae2c7f039644daad6452fb300da7b28d, relevant bit starting around 1:54:36

### Notes

I'm not fully sure what causes this.  The `mirror` function of BlockBarracksTowerSubstitution.java looks reasonable so I'd at least expect this to show up correctly in the previews.  I notice that `AbstractBlockHut.java` doesn't have a `mirror` function even though it does have `rotate`, and a bit more work might need to be done to pass the mirror bit down to the hut block's building, though.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dhouck** [comment]
(Oh, forgot to mention for issue linking purposes, this was found from https://github.com/ldtteam/minecolonies/issues/5006#issuecomment-856323324)

**Comment by Raycoms** [comment]
Gonna be fixed in 1.17, need to adjust block rotations correctly.

**Comment by dhouck** [comment]
The barracks changes donʼt actually solve this issue; mirrored sub-buildings (including, but not limited to, barracks towers) still do not work.  I probably should have tested that a year ago when the issue was closed, but itʼs still well-known on Discord to not be solved.

**Comment by dhouck** [comment]
Given that this is still an issue despite being closed, should I make a new one about it?  Unless I get a reply I plan to test it once the build tool rework is out and create a new issue if so.
