### ISSUE TITLE
Exception Ticking world

### ISSUE THREAD

**Issue by Nick777777712** [ldtteam/minecolonies#8041]
### Prerequisites 

- [ y] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [y ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [y ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:1.18.1
- Structurize Version:1.18.1
- Related Mods and their Versions:1.18.1

## Expected behavior
Not crash after 4 minutes has gone by in game

## Actual behavior
 So now I can play with the colony for about 4 minutes and then it crashes yet again

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

<script src="https://gist.github.com/Nick777777712/f5357e7bf7093332efbdc3e948c7fa3a.js"></script>

- latest.log: 
- crashlog: 

### Notes

If u need to another email you can reach me by is 1vangemertni@hdsb.ca
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Don;t just keepmaking new issues with the same problem. This was fixed as mentioned in the other issue. Update

**Comment by Nick777777712** [comment]
But I did update everything and it still occurs I'm sorry I didn't realize
that it is the same problem. I just don't know how to fix it

**Comment by Raycoms** [comment]
update to the latest beta that we uploaded today

**Comment by Nick777777712** [comment]
Will do

**Comment by Nick777777712** [comment]
May I email back here if I still have troubles?

**Comment by Raycoms** [comment]
Yes, you can post here again

**Comment by Nick777777712** [comment]
Problem is still going on <script src="
https://gist.github.com/Nick777777712/147044865fc939c8bfd4aaf68121a41a.js"></script>
Everyhing i believe is the right version

**Comment by Talyda** [comment]
With the full disclaimer that I can't read logs - can you try starting up without Alex's mobs?
Oh, no wait, it's something else, just a sec

**Comment by Talyda** [comment]
Can you check inside your mods folder and make sure the old versions were deleted

**Comment by Talyda** [comment]
And if not, then I would try without alex's mobs

**Comment by Nick777777712** [comment]
Will do
