### ISSUE TITLE
Unable to access Minecolony GUIs

### ISSUE THREAD

**Issue by thelordofdino4** [ldtteam/minecolonies#807]
### Minecolonies version

version 0.7.3.5

### Expected behavior

- Going to blocks or workers and clicking will open a gui to interact with

### Actual behaviour

- GUIs don't appear

### Steps to reproduce the problem

All I can recall is that the game was going to save and exit to main menu the last time this happened, but I had to force the game to close. This was happening before I updated, and I don't believe this is what happened last time. Not sure if I go into another world and attempt to make a new town if it will occur again. Any help is appreciated. 

Edit: Yes, I have attempted to refresh using ./mc colony refresh. It does not work.

**Comment by marchermans** [comment]
Can you post a log in like a PasteBin or a GitHub Gist or something like that?

**Comment by Raycoms** [comment]
can you execute /mc colonies list
then /mc colony info id (of your colony)
then /mc colony refresh id (if that fixes it)

2017-04-15 4:53 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by thelordofdino4** [comment]
@Raycoms I tried all of that and it never worked. However I found a temporary fix to the bug, but an annoying fix at that. If I encounter the glitch where I can no longer open any GUI's related to minecolony, if I exit to the main menu, create a new creative map, place down a town hall, open the GUI, exit to main menu, and go back to the world that I was encountering the glitch in, I can open the GUIs for minecolonies in that map. It's so  weird and makes no logical sense, but I've reproduced it twice now.

**Comment by Raycoms** [comment]
Unfortunately, we were never able to reproduce that bug in our dev
environment.

what does /mc colony info id tell you?

2017-04-15 18:40 GMT-03:00 thelordofdino4 <notifications@github.com>:

**Comment by thelordofdino4** [comment]
Quoting directly it says
ID:1 Name: (my minecraft username)'s Colony
Mayor:(my user name)
Citizens: 4/4
Coordinates: x=549 y=75 Z=218

I should probably also mention that I'm using a modified version of the mod pack "All the mods" while running mine colonies, alongside some other mods such as mo' creatures, jurrasic craft 2, modular force fields, and a few others. It takes 9 gb of ram to run :P

**Comment by gd71** [comment]
Hello,
I had similar issues several times and I fixed it by restoring a previous minecolonies.dat file, thanks to the automatic backup.
The file can be corrupted by a forced closure of minecraft but also less frequently by an update of the mod.
Please also note that using nbtexplorer doesn't seem to reveal errors on that .dat file and display structure correctly most of the time. Might be also some non-printable chars inside the file but I didn't investigate deeper on this way.
Hope this can help

**Comment by Raycoms** [comment]
We are working on this, but it seems some kind of dataloss we can't explain yet.

**Comment by nastanford** [comment]
Why was it closed? This is still an issue?  Hope it gets fixed. I love playing.

**Comment by nastanford** [comment]
If I use an old version of Minecraft will that fix the issue? or is it on all versions.

**Comment by mkienenb** [comment]
It's been several months.  Have you tried it recently?

**Comment by nastanford** [comment]
Yes, just had this happen to me and was searching and found this issue. I will try to update.  Is there a version of MC I should be using?

**Comment by nastanford** [comment]
I will start a new colony after work and used that mod only to see if I have any issues.

**Comment by Raycoms** [comment]
Try the newest: https://minecraft.curseforge.com/projects/minecolonies

**Comment by mkienenb** [comment]
Also, please check your logs to see if there are any errors logged there.

**Comment by nastanford** [comment]
Does the twitch/curse client download the latest Mod?

**Comment by nastanford** [comment]
![image](https://user-images.githubusercontent.com/1755947/35939133-3c731018-0c19-11e8-95ec-fe72ba76b5ce.png)

**Comment by Raycoms** [comment]
It often downloads the release, I think you have to specify you want the alpha.

**Comment by nastanford** [comment]
So is this not a good file? the minecolonies-universal-1.12.2-0.8.6934.jar?

**Comment by Raycoms** [comment]
No you should try it with 7455

2018-02-07 20:22 GMT+00:00 Nathan Stanford Sr <notifications@github.com>:

**Comment by nastanford** [comment]
How do I get the Twitch/Curse Client to download alpha?

**Comment by nastanford** [comment]
I found it.  Trying it now. Thanks

**Comment by hron84** [comment]
Suddenly it happened for me too with 7375 under 1.10. @Raycoms can you make a command that overrides every protection and let access the colony for admins / in creative if SSP?
Because I can't even access my colony after disabling protection in config files.

Also, I'm not sure if it is related to ToroQuest since I had quite good reputation to not refuse me to open blocks / inventories in the area.

**Comment by Raycoms** [comment]
Probably your colony got lost, please load a backup of your colonyX.dat
file in world/minecolonies.

2018-02-18 9:29 GMT+00:00 Gabor Garami <notifications@github.com>:

**Comment by hron84** [comment]
@Raycoms what can cause problem like this? Also, `/minecol colony info Dragonia` described the colony correctly and named me as an owner, but still did not let me access GUIs

**Comment by Raycoms** [comment]
Crashes sometimes corrupt the data when saving
