### ISSUE TITLE
[BUG] Stonemason unable to craft smooth stone slabs

### ISSUE THREAD

**Issue by Epig-is-a-llama** [ldtteam/minecolonies#8160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.503

### Structurize Version

1.0.354-ALPHA

### Related Mods and their Versions

1. 36.2.31
2. N/A

### Current Behavior

Stonemason cannot craft smooth stone slabs.
![image](https://user-images.githubusercontent.com/60323417/159097019-ca9a8e12-bb59-47dd-b645-0cab37f8bf75.png)
![image](https://user-images.githubusercontent.com/60323417/159097023-263a0975-83b8-4a7c-aff7-5c82136802b2.png)
![image](https://user-images.githubusercontent.com/60323417/159097071-c2a96af0-92d1-4ec6-af85-4b2e2c1a2018.png)

### Expected Behavior

Stone mason will be able to craft it.

### Reproduction Steps

1. Try to teach a stone mason to craft the above mentioned block.
2. Get a chat message saying that they cannot despite sufficient space.

### Logs

*no log entry since over 15mins prior to the issue and none since at time of writing*

### Anything else?

While I have not personally tested on the latest alpha the person that asked me to make a ticket on the discord server. the moderator `MotionlessTrain#0397` has done such tests and confirmed identical behaviour to that which I am experiencing.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
They probably meant 1.0.503, that was the version they posted on discord :D

**Comment by Epig-is-a-llama** [comment]
My bad, I clearly misread the 3 as a 5 when writing, sorry. Shall I edit it to fix?

**Comment by MotionlessTrain** [comment]
Yeah, that could clear up some possible confusion, I would think

**Comment by Epig-is-a-llama** [comment]
Fixed, when editing i spotted i wrote `305` not `503`, which is most likely where I got that 3 from.

**Comment by MotionlessTrain** [comment]
Why was this closed?
It is still present in 1.0.507.
Is it intended that the stone mason can't craft recipes with smooth stone?

**Comment by Raycoms** [comment]
Ah, I understood it was fixed. =P

**Comment by MotionlessTrain** [comment]
They meant they fixed their typo in the "MineColonies version" field :D
