### ISSUE TITLE
[BUG] <The "priority" function does not work>

### ISSUE THREAD

**Issue by Sirius254** [ldtteam/minecolonies#8307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.429-RELEASE

### Structurize Version

1.0.343-RELEASE

### Current Behavior

 The "priority" function in buildings does not work for me. The numbers in the "priority" are not displayed. "+" and "-" do not work.
This problem occurs only when changing the game language to Russian.
Everything is displayed in English.

![Screenshot_4](https://user-images.githubusercontent.com/104667085/166092379-ca165af5-0c3b-4608-99e5-d6d8556f898c.png)

### Expected Behavior

I want the "priority" function to work in Russian.

### Reproduction Steps

Play the game in Russian.

### Logs

https://gist.github.com/Sirius254/403ab61c1011039a12d2bd2df353528d

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Have you tried it on the latest alpha?

**Comment by Sirius254** [comment]
Нет.
Я не хочу терять прогресс в своей игре.

> Вы пробовали это на последней альфе?

**Comment by uecasm** [comment]
Upgrading the mod does not cause you to lose progress.  (Though as with any upgrade, make a backup of your save first.)  The version you are using is ancient and many bugs have been fixed since then, which is why we ask people to try the latest alpha before reporting anything.

**Comment by Sirius254** [comment]
Ok, I'll try

**Comment by Sirius254** [comment]
I have updated to the latest alpha version. The problem is not solved.

**Comment by Raycoms** [comment]
double checked into it, seems to be a translation issue with the Russian translation. Please check on translate.minecolonies.com for that

**Comment by Sirius254** [comment]
Where to put the "scr" folder?
