### ISSUE TITLE
[BUG] Can't select any Fuel

### ISSUE THREAD

**Issue by RhagVreal** [ldtteam/minecolonies#8627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1004- Alpha

### Structurize Version

1.19.2-1.0.443-ALPHA

### Related Mods and their Versions

1. Forge Version: 43.1.1
2. Block UI Version: 1.19-0.0.61-ALPHA
3. domum_ornamentum 1.19-1.0.59-ALPHA

Here is my Modlist:
![image](https://user-images.githubusercontent.com/110904169/188601733-23c15298-70fd-44a7-972a-708cf94a69b8.png)

### Current Behavior

I can't select any Fuel in Restaurant:

![image](https://user-images.githubusercontent.com/110904169/188601427-7de82f95-a164-40b0-b6e4-9d2519bc99db.png)

### Expected Behavior

I wan't to select any Fuel for the Cook in the Restaurant

### Reproduction Steps

1. Click on Restaurant Hut
2. Select Fuel Tab
3. Nothing is shown there

### Logs

https://gist.github.com/RhagVreal/4b00117218dc2c4fb87d61ac4f526751

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Try to leave the server and join it again

**Comment by RhagVreal** [comment]
After 4 Restarts it finally worked.
Thank you

**Comment by jaredniegas** [comment]
Does anyone know what causes this bug? I hope it gets fixed. It's happening to me constantly.

**Comment by MotionlessTrain** [comment]
This has been fixed already, in minecolonies 1.0.1029+ (1.18.2) or 1.0.1031+ (1.19.2)

**Comment by jaredniegas** [comment]
I'm on 1.0.1030 (1.18.2) and it still happens. Should I go for the latest alpha?
    On Monday, September 19, 2022 at 12:18:12 AM GMT+8, MotionlessTrain ***@***.***> wrote:  
 
 


This has been fixed already, in minecolonies 1.0.1029+ (1.18.2) or 1.0.1031+ (1.19.2)

**Comment by MotionlessTrain** [comment]
The latest alpha is usually a good idea

**Comment by MotionlessTrain** [comment]
If updating the server and client to the latest alpha doesn't help, could you provide your latest.log please? Preferably both the one from the server and the client
