### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by MrAek546** [ldtteam/minecolonies#8922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.12.00BETA

### Structurize Version

1.0.472-BETA

### Related Mods and their Versions

Forge Version is 43.2.3

### Current Behavior

When updating from 1.0.9 to 1.0.12 the alternative Pagoda guard tower was removed as an option, on previous version there were two styles and now there's only one.  This broke a dozen towers I had set up!  Was this schematic removed on purpose?  

### Expected Behavior

When building a guard tower on Pagoda style there should be two options for the style.

### Reproduction Steps

try pagoda style guard tower on older version and newer version and you'll notice the alt style missing.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Was fixed in latest

**Comment by MrAek546** [comment]
Hello, I just updated to the latest version of Minecolones, on 1.19.2 - 1.0.1210 and the alt2 guard tower for Pagoda is still missing.  it was there on earlier versions.

**Comment by Raycoms** [comment]
1.0.1213

**Comment by MrAek546** [comment]
Yeah, I saw that, sorry right after I realized there were alphas on the download that weren't in the "recent"
