### ISSUE TITLE
[BUG] GameCrash when I open Barracks BuildMenu 

### ISSUE THREAD

**Issue by Fors3ti** [ldtteam/minecolonies#8938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1226-BETA.jar

### Structurize Version

1.19.2-1.0.480-ALPHA.jar

### Related Mods and their Versions

Forge Version: 43.2.0
Block UI: 1.19-0.0.64-ALPHA.jar
Domum Ornamentum: 1.19-1.0.76-ALPHA-universal.jar

### Current Behavior

The Game is crashing, when i open the Builder GUI from the Baracks

### Expected Behavior

-

### Reproduction Steps

1. Build Baracks
2. Open Baracks Buildoptions
3. Game Crash 

### Logs

https://pastebin.com/kySS7nti

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This has been fixed already

**Comment by budgej** [comment]
This is unfortunately not fixed.  I've still been seeing this error for a few days when placing courier huts - Assign to Builder, Constructed, or Schematic.

https://pastebin.com/XrDyK1bA

**Comment by Talyda** [comment]
Can you update and try again please @budgej - you're 18 version numbers out of date
