### ISSUE TITLE
[1.11.2- 0.7.887

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#953]
no idea what's causing the crash

https://paste.ee/p/40Et9

**Comment by Raycoms** [comment]
Its the newest alpha on curse?

2017-05-08 19:37 GMT-03:00 Wilson Gonzales <notifications@github.com>:

**Comment by wilsondgonzales** [comment]
@Raycoms yes. the colony loads, then everyone complains about being hungry, then crash

**Comment by wilsondgonzales** [comment]
Also started a new map and dropped a townhall. i noticed that the colonists have weird names like

*Shannon I. White P. Williams* lol

**Comment by Raycoms** [comment]
Haha nice catch, fixed that together with that crash.
Will paste a working version here in a moment.

**Comment by Raycoms** [comment]
http://teamcity.smithsmodding.com/guestAuth/repository/download/Minecolonies_Branches/909:id/minecolonies-universal-1.11.2-0.7.909.jar

**Comment by wilsondgonzales** [comment]
fast fix! i'll try in a bit

**Comment by wilsondgonzales** [comment]
now i have the same error as #949 but here's the log https://paste.ee/p/IpZj7
i guess it's also safe to close or should i be closing the issue?

**Comment by Raycoms** [comment]
http://teamcity.smithsmodding.com/guestAuth/repository/download/Minecolonies_Branches/917:id/minecolonies-universal-1.11.2-0.7.917.jar

Should fix this

**Comment by wilsondgonzales** [comment]
@Raycoms this fixed it. however the problem persists on 0.7.920 which was released on curse

**Comment by Raycoms** [comment]
920 was released when on curse?

2017-05-09 14:04 GMT-03:00 Wilson Gonzales <notifications@github.com>:

**Comment by wilsondgonzales** [comment]
@Raycoms  https://minecraft.curseforge.com/projects/minecolonies/files/2417809 
i might be confused about what 'curse' is

**Comment by Raycoms** [comment]
@Kostronor why might it work in my demo build and not in the curse version?

2017-05-09 14:18 GMT-03:00 Wilson Gonzales <notifications@github.com>:

**Comment by wilsondgonzales** [comment]
@Raycoms the latest .930 works. Note (something i'll start a new thread for) that colonists spawn with all attributes at 1. I've killed a bunch to get colonists with the right attributes for a job but now have a bunch of em with 1s across all attributes. if it was intended that they level up as they go, great
